# Generated by Django 4.1 on 2023-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('item', models.CharField(max_length=200, verbose_name='Product')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('deal_date', models.DateTimeField(verbose_name='Deal Date')),
            ],
            options={
                'verbose_name_plural': 'Deals',
            },
        ),
    ]
